-- EpiEvidence PostgreSQL baseline schema.
-- IDs are generated by the backend and supplied as UUID values.

BEGIN;

CREATE TABLE IF NOT EXISTS tasks (
    task_id UUID PRIMARY KEY,
    conversation_id UUID,
    client_request_id TEXT,
    user_query TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    error_type TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,

    CONSTRAINT ck_tasks_user_query_not_blank
        CHECK (length(btrim(user_query)) > 0),
    CONSTRAINT ck_tasks_status
        CHECK (status IN (
            'created',
            'recognizing_intent',
            'searching',
            'screening',
            'awaiting_user_selection',
            'completed',
            'failed',
            'cancelled'
        )),
    CONSTRAINT ck_tasks_completion_time
        CHECK (completed_at IS NULL OR completed_at >= created_at),
    CONSTRAINT uq_tasks_client_request_id
        UNIQUE (client_request_id)
);

CREATE TABLE IF NOT EXISTS search_runs (
    search_run_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    source TEXT NOT NULL,
    compiled_query TEXT NOT NULL,
    query_hash CHAR(64),
    status TEXT NOT NULL DEFAULT 'pending',
    hit_count INTEGER,
    retrieved_count INTEGER NOT NULL DEFAULT 0,
    page_count INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_search_runs_task
        FOREIGN KEY (task_id)
        REFERENCES tasks (task_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_search_runs_source_not_blank
        CHECK (length(btrim(source)) > 0),
    CONSTRAINT ck_search_runs_query_not_blank
        CHECK (length(btrim(compiled_query)) > 0),
    CONSTRAINT ck_search_runs_query_hash
        CHECK (query_hash IS NULL OR query_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_search_runs_status
        CHECK (status IN (
            'pending',
            'running',
            'success_with_results',
            'success_empty',
            'partial_success',
            'failed'
        )),
    CONSTRAINT ck_search_runs_counts
        CHECK (
            (hit_count IS NULL OR hit_count >= 0)
            AND retrieved_count >= 0
            AND page_count >= 0
            AND retry_count >= 0
        ),
    CONSTRAINT ck_search_runs_completion_time
        CHECK (
            completed_at IS NULL
            OR started_at IS NULL
            OR completed_at >= started_at
        )
);

CREATE TABLE IF NOT EXISTS articles (
    article_id UUID PRIMARY KEY,
    doi TEXT,
    pmid TEXT,
    pmcid TEXT,
    title TEXT NOT NULL,
    normalized_title TEXT NOT NULL,
    abstract TEXT,
    abstract_available BOOLEAN GENERATED ALWAYS AS (
        abstract IS NOT NULL AND length(btrim(abstract)) > 0
    ) STORED,
    first_author TEXT,
    authors JSONB NOT NULL DEFAULT '[]'::JSONB,
    journal_title TEXT,
    journal_abbreviation TEXT,
    issn TEXT,
    electronic_issn TEXT,
    publication_date DATE,
    publication_year SMALLINT,
    publication_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    study_design TEXT,
    publication_status TEXT,
    language TEXT,
    is_retracted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_articles_title_not_blank
        CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_articles_normalized_title_not_blank
        CHECK (length(btrim(normalized_title)) > 0),
    CONSTRAINT ck_articles_doi_not_blank
        CHECK (doi IS NULL OR length(btrim(doi)) > 0),
    CONSTRAINT ck_articles_pmid
        CHECK (pmid IS NULL OR pmid ~ '^[0-9]+$'),
    CONSTRAINT ck_articles_pmcid
        CHECK (pmcid IS NULL OR pmcid ~* '^PMC[0-9]+$'),
    CONSTRAINT ck_articles_authors_array
        CHECK (jsonb_typeof(authors) = 'array'),
    CONSTRAINT ck_articles_publication_year
        CHECK (
            publication_year IS NULL
            OR publication_year BETWEEN 1500 AND 3000
        )
);

CREATE TABLE IF NOT EXISTS source_records (
    source_record_pk UUID PRIMARY KEY,
    search_run_id UUID NOT NULL,
    article_id UUID,
    source_record_id TEXT NOT NULL,
    source_rank INTEGER,
    raw_payload JSONB NOT NULL,
    payload_hash CHAR(64),
    normalization_status TEXT NOT NULL DEFAULT 'pending',
    normalization_error TEXT,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    normalized_at TIMESTAMPTZ,

    CONSTRAINT fk_source_records_search_run
        FOREIGN KEY (search_run_id)
        REFERENCES search_runs (search_run_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_source_records_article
        FOREIGN KEY (article_id)
        REFERENCES articles (article_id)
        ON DELETE SET NULL,
    CONSTRAINT uq_source_records_per_run
        UNIQUE (search_run_id, source_record_id),
    CONSTRAINT uq_source_records_article_pair
        UNIQUE (source_record_pk, article_id),
    CONSTRAINT ck_source_records_id_not_blank
        CHECK (length(btrim(source_record_id)) > 0),
    CONSTRAINT ck_source_records_rank
        CHECK (source_rank IS NULL OR source_rank >= 1),
    CONSTRAINT ck_source_records_payload_object
        CHECK (jsonb_typeof(raw_payload) = 'object'),
    CONSTRAINT ck_source_records_payload_hash
        CHECK (payload_hash IS NULL OR payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_source_records_normalization_status
        CHECK (normalization_status IN ('pending', 'success', 'failed')),
    CONSTRAINT ck_source_records_normalized_at
        CHECK (
            normalized_at IS NULL
            OR normalized_at >= retrieved_at
        )
);

CREATE TABLE IF NOT EXISTS full_text_resources (
    resource_id UUID PRIMARY KEY,
    article_id UUID NOT NULL,
    source_record_pk UUID NOT NULL,
    resource_url TEXT NOT NULL,
    landing_url TEXT,
    format TEXT NOT NULL,
    original_style TEXT,
    availability TEXT,
    availability_code TEXT,
    is_open_access BOOLEAN,
    is_downloadable BOOLEAN,
    is_preferred BOOLEAN NOT NULL DEFAULT FALSE,
    suggested_file_name TEXT,
    discovered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_full_text_resources_article
        FOREIGN KEY (article_id)
        REFERENCES articles (article_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_full_text_resources_source_article
        FOREIGN KEY (source_record_pk, article_id)
        REFERENCES source_records (source_record_pk, article_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_full_text_resources_article_url
        UNIQUE (article_id, resource_url),
    CONSTRAINT ck_full_text_resources_url
        CHECK (resource_url ~* '^https?://'),
    CONSTRAINT ck_full_text_resources_landing_url
        CHECK (landing_url IS NULL OR landing_url ~* '^https?://'),
    CONSTRAINT ck_full_text_resources_format
        CHECK (format IN ('pdf', 'epub', 'html', 'xml', 'text', 'other')),
    CONSTRAINT ck_full_text_resources_preferred_downloadable
        CHECK (NOT is_preferred OR is_downloadable IS TRUE)
);

CREATE INDEX IF NOT EXISTS ix_tasks_conversation_created
    ON tasks (conversation_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_tasks_status
    ON tasks (status);

CREATE INDEX IF NOT EXISTS ix_search_runs_task_created
    ON search_runs (task_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_search_runs_source_status
    ON search_runs (source, status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_articles_doi_normalized
    ON articles ((lower(btrim(doi))))
    WHERE doi IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_articles_pmid
    ON articles (pmid)
    WHERE pmid IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_articles_pmcid_normalized
    ON articles ((upper(btrim(pmcid))))
    WHERE pmcid IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_articles_normalized_title
    ON articles (normalized_title);

CREATE INDEX IF NOT EXISTS ix_articles_publication_date
    ON articles (publication_date DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS ix_articles_publication_types
    ON articles USING GIN (publication_types);

CREATE INDEX IF NOT EXISTS ix_source_records_search_rank
    ON source_records (search_run_id, source_rank);

CREATE INDEX IF NOT EXISTS ix_source_records_article
    ON source_records (article_id)
    WHERE article_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_source_records_normalization_status
    ON source_records (normalization_status);

CREATE INDEX IF NOT EXISTS ix_full_text_resources_article
    ON full_text_resources (article_id);

CREATE INDEX IF NOT EXISTS ix_full_text_resources_downloadable
    ON full_text_resources (article_id, format)
    WHERE is_downloadable IS TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_full_text_resources_preferred_article
    ON full_text_resources (article_id)
    WHERE is_preferred IS TRUE;

COMMENT ON TABLE tasks IS
    'Backend-created research tasks originating from user queries.';
COMMENT ON TABLE search_runs IS
    'One provider-specific search execution within a research task.';
COMMENT ON TABLE articles IS
    'Canonical articles after cross-source normalization and deduplication.';
COMMENT ON TABLE source_records IS
    'Raw provider records retained per search run for provenance and replay.';
COMMENT ON TABLE full_text_resources IS
    'Discovered full-text candidates; this table does not record completed downloads.';

COMMIT;
